name: Report PDF

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Convert ipynb to md
      run: pip install nbconvert && cd Lab5 && make markdown
    - uses: docker://pandoc/latex:2.9
    - name: Convert md to PDF
      run: cd Lab5 && make pdf  
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: report.pdf
        # A file, directory or wildcard pattern that describes what to upload
        path: Lab5/report/report.pdf
      # The desired behavior if no files are found using the provided path.
